### ISSUE TITLE
Configuration should have sensible defaults and only a few mandatory fields

### ISSUE THREAD

**Issue by md-5** [atheme/iris#3]
Currently https://gist.github.com/a2b69a74bda308a22bed is the minimum amount of configuration required to get an iris server running. In comparison to say Charybdis and other products which default to hard coded values in the event a configuration value is not set. Charybdis for example can run fine on https://gist.github.com/e038e6d985a6152caa4e

What I am suggesting is that almost every option, bar irc server and network name, maybe a few others get a default option and that they need not be specified in the configuration.

Thanks
md_5

**Comment by GLolol** [comment]
:+1:

**Comment by kaniini** [comment]
Shouldn't you just use kiwi-irc by now?

**Comment by GLolol** [comment]
Iris has a cleaner interface.

**Comment by megawac** [comment]
You can also consider using my fork of Iris&qweb https://github.com/megawac/qwebirc-enhancements + https://github.com/megawac/iris

**Comment by md-5** [comment]
Yeah iris is far better than kiwi. Eventually I'll move to qwebirc or a fork.
