### ISSUE TITLE
Compile process aborts

### ISSUE THREAD

**Issue by seegras3** [atheme/iris#46]
Hi,
while trying to compile iris on my debian 7 vps, the process aborts with the following lines

> irisirc@vps2:~/iris$ python compile.py
> Traceback (most recent call last):
> File "compile.py", line 2, in <module>
> import bin.compile
> File "/home/irisirc/iris/bin/compile.py", line 5, in <module>
> import pages, os, subprocess, pagegen, shutil, sys, time
> File "/home/irisirc/iris/bin/pagegen.py", line 2, in <module>
> import qwebirc.config as config
> File "/home/irisirc/iris/qwebirc/config.py", line 143, in <module>
> load_config()
> File "/home/irisirc/iris/qwebirc/config.py", line 23, in load_config
> check_config(True)
> File "/home/irisirc/iris/qwebirc/config.py", line 30, in check_config
> raise ConfigParser.NoSectionError(section)
> ConfigParser.NoSectionError: No section: 'adminengine'

how can I solve this problem?

**Comment by grawity** [comment]
The last line says:

> ConfigParser.NoSectionError: No section: 'adminengine'

Have you tried adding an `[adminengine]` section to the config?
